version: '3.8'  # Specify the version of Docker Compose

services:
  mysql:
    image: mysql:8.0    # Use the MySQL 8.0 image
    container_name: mysql-container  # Optional: name of the container
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Root password for MySQL
      MYSQL_DATABASE: mydatabase  # Default database to be created
      MYSQL_USER: user  # Optional: create a user
      MYSQL_PASSWORD: user_password  # Optional: password for the user
    ports:
      - "3306:3306"  # Expose port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data

volumes:
  mysql_data: